### ISSUE TITLE
LXD provisioning for kubernetes isnt working

### ISSUE THREAD

**Issue by ranema1987** [justmeandopensource/kubernetes#122]
Hi,

i tried the below script  but its not working.
https://github.com/justmeandopensource/kubernetes/tree/master/lxd-provisioning

appreciate if someone help, excellent if owner himself reply.

**Comment by ak2766** [comment]
You really have to provide more info than that to get any help.  At the very least, which part in those instructions caused you grief?  Show the command you run and what output you got that was unexpected.  Otherwise, your question just prompts us to ask you to explain - like I'm doing here.  Total waste of time.

**Comment by justmeandopensource** [comment]
@ranema1987 thanks for reporting your issue.
There were some problems with the lxd provisioning for a while and i had success running them on my Linux host. I am currently working on updating the lxd provisioning scripts to use the latest versions of container runtime and k8s version. Hopefully you can use the updated scripts without issues once they are ready. And it would be helpful to help you if we know the context better like what OS you are trying, what error you are getting at what step, pasting actual command outputs and errors etc. Thanks.
